require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '254715155196',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'CYTRA-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUZ2czlJMlFQMXBWK3ZmZXN2ZERiWm5mVjR3c3RYaytIcjVkUFArSDdGST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUhsZW9zdHp0dkNtTjJvb3ZwcUhkeUV6QlI2M2JGSjMvZFRBenJlVjNRST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDS253SXlOTUFWNmd3WHJtRnUrbHBzK2NtZTQxenVuZkFEdkw5SHY3YWxvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTL2tLZDM2akY2Wjc5b05NTCtYN1B1cXc0MlZXdm11TnNGRkRkWWdCZFNNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFPZnBsT2dDblVQY20zVnRuTXpabjRHWnFFcENWMk84akM0NnkyZUFubWM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFRSmRQZitnV3pxaFlUUmt4S0ZuSjJJY1BXTHNrenVDWG1COWltYWNvemc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUl3M1YrVDdnNm8zYXg1ZitTRzhneWs5cVRYejdsNkNqbFZheUZYeXptaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0hPVkw0dG1RTkRTUzdqT0RkUlRKbzVUM2ppbXBtSURWVHp6OWR3RkRCQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklmNzNnNjJFTlZZTTRXdjk5bE44elpOSDA2SzdBajNmaEI3L1NBOWhRTldmdVZyZEVzbnVrcFk3UG1PS3doVlhGRUthQ3o5UG9vdDB4Mk10eCt6VkR3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODYsImFkdlNlY3JldEtleSI6InlsM050MXhXUE9zWVRld0VUR2tDVjhPV3RoUCsyZFd3SFVXcXNRM0J0Wkk9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzE1MTU1MTk2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkNBRTJFQUZFODQ1QjNERjhCMTZBN0Q2NThFMjQyODlEIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTQ2MzM3NDZ9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDcxNTE1NTE5NkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIyMzRFQkEwMTRFODQyRkMwQkE5MTUwNzJGQkYyREIyQSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzU0NjMzNzYwfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3MTUxNTUxOTZAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQTdCMzhGQjc5RjI5NkIzQjg3RDVBNkUwMjY4QjVCNTUifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NDYzMzc3Nn1dLCJuZXh0UHJlS2V5SWQiOjM2LCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzYsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiSFNGUzRGM1QiLCJtZSI6eyJpZCI6IjI1NDcxNTE1NTE5NjoxOEBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjE0NjEyMzgxMzU1MjE1NToxOEBsaWQiLCJuYW1lIjoiU01LIOKAoiBDWVRSQSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSUxybk80REVJR3Mxc1FHR0JFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiTkpPdVZlVk5qUEJ4QWNHSWJqRlpJVHJreFMyVEdvNjA2OUZZeHRPc29BOD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiNGkzRll3eFJaZmRERllHZUFITnFaMFZjRDlONlcvUmpDQ1p3ODZpa2ZwZ1ZJQ0w0MER4TnVFMnlieVZFWjV4WGlKV29IRUZ5b0tmUWlDUGRmTU9RQUE9PSIsImRldmljZVNpZ25hdHVyZSI6ImFtSyt3VjBDNDBwQThWbjlJNmtZSmRWbDlHMW5TajltR2l0ZWZQS2RSOXpDOVNCT1Vra2NuVmNwbERjRkd3SjBkQWdGckJWTDlaTTJWaWVHYjJ5VUJ3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzE1MTU1MTk2OjE4QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlRTVHJsWGxUWXp3Y1FIQmlHNHhXU0U2NU1VdGt4cU90T3ZSV01iVHJLQVAifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBZ0lFZz09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1NDYzMzc0MiwibGFzdFByb3BIYXNoIjoiMUs0aEg0IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFKV04ifQ==',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
